"""add industry

Revision ID: 67fc3a0137cf
Revises: 860db187515d
Create Date: 2018-06-13 17:17:59.429854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fc3a0137cf'
down_revision = '860db187515d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('industry', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'industry')
    # ### end Alembic commands ###
