"""add title for template

Revision ID: 860db187515d
Revises: 90e46e3d3c40
Create Date: 2018-06-13 16:44:30.845523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860db187515d'
down_revision = '90e46e3d3c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('title', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'title')
    # ### end Alembic commands ###
