"""add manager

Revision ID: 90e46e3d3c40
Revises: c732a8c1992b
Create Date: 2018-06-13 16:27:59.499943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e46e3d3c40'
down_revision = 'c732a8c1992b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_username'), 'manager', ['username'], unique=True)
    op.create_index(op.f('ix_template_template_id'), 'template', ['template_id'], unique=True)
    op.create_index(op.f('ix_user_open_id'), 'user', ['open_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_open_id'), table_name='user')
    op.drop_index(op.f('ix_template_template_id'), table_name='template')
    op.drop_index(op.f('ix_manager_username'), table_name='manager')
    op.drop_table('manager')
    # ### end Alembic commands ###
